export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      name: "cd",
      description: "Server para abrir pasta",
      language: "bashBasico",
      link: "https://pt.dnys.dev",
    },
    {
      id: 2,
      name: "ls",
      description: "Listar todos arquivos",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
    {
      id: 3,
      name: "mkdir",
      description: "Criar pasta",
      language: "bashBasico",
      link: "https://teste-proz.daviny.dev/",
    },
    {
      id: 4,
      name: "chmod",
      description: "Permições de acesso tanto arquivo ou pasta",
      language: "bashBasico",
      link: "https://teste-proz.daviny.dev/",
    },
    {
      id: 5,
      name: "top",
      description: "Mostra todos processos e o tamanho de uso de memória.",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
    {
      id: 6,
      name: "login",
      description: "Cancela a sessão atual e inicia uma nova sessão de usuário.",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
    {
      id: 7,
      name: "man",
      description: "Consulta os manuais online do sistema.",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
    {
      id: 8,
      name: "halt",
      description: "Desliga o computador.",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
    {
      id: 9,
      name: "exit",
      description: "Encerra o shell dos comandos recentes.",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
    {
      id: 10,
      name: "pwd",
      description: "Exibe o caminho do diretório corrente.",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
    {
      id: 11,
      name: "find",
      description: "São usado para localizar arquivos e palavras dentro deste.",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
    {
      id: 12,
      name: "clear",
      description: "Limpar a tela do terminal virtual corrente.",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
    {
      id: 13,
      name: "bg",
      description: "Coloca um processo em segundo plano (blackground).",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
    {
      id: 14,
      name: "fg",
      description: "Coloca um processo em primeiro plano (foreground)",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
    {
      id: 15,
      name: "kill",
      description: "Finaliza um job. Esse camando é um comando interno do shell, não deve confundir com programa kill é um programa executável.",
      language: "bashBasico",
      link: "https://commands.views.page",
    },
]);
}