export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      name: "cd",
      description: "Server para abrir pasta",
      language: "bashBasico",
      link: "https://pt.dnys.dev",
    },
    {
      id: 2,
      name: "ls",
      description: "Listar todos arquivos",
      language: "bashBasico",
      link: "https://run.dnys.dev",
    },
    {
      id: 3,
      name: "mkdir",
      description: "Criar pasta",
      language: "bashBasico",
      link: "https://teste-proz.daviny.dev/",
    },
    {
      id: 4,
      name: "chmod",
      description: "Permições de acesso tanto arquivo ou pasta",
      language: "bashBasico",
      link: "https://teste-proz.daviny.dev/",
    },
    {
      id: 5,
      name: "top",
      description: "Mostra todos processos e o tamanho de uso de memória.",
      language: "bashBasico",
      link: "https://run.dnys.dev",
    },
    {
      id: 6,
      name: "login",
      description: "Cancela a sessão atual e inicia uma nova sessão de usuário.",
      language: "bashBasico",
      link: "https://run.dnys.dev",
    },
    {
      id: 7,
      name: "man",
      description: "Consulta os manuais online do sistema.",
      language: "bashBasico",
      link: "https://run.dnys.dev",
    },
    {
      id: 8,
      name: "halt",
      description: "Desliga o computador.",
      language: "bashBasico",
      link: "https://run.dnys.dev",
    },
    {
      id: 9,
      name: "exit",
      description: "Encerra o shell dos comandos recentes.",
      language: "bashBasico",
      link: "https://run.dnys.dev",
    },
    {
      id: 10,
      name: "pwd",
      description: "Exibe o caminho do diretório corrente.",
      language: "bashBasico",
      link: "https://run.dnys.dev",
    },
    {
      id: 11,
      name: "find",
      description: "São usado para localizar arquivos e palavras dentro deste.",
      language: "bashBasico",
      link: "https://run.dnys.dev",
    },
]);
}